CREATE TABLE User (
id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
Firstname VARCHAR(250),
Lastname VARCHAR(250),
Email VARCHAR(250) UNIQUE,
Password VARCHAR(250)
);

CREATE TABLE Director(
id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
Firstname VARCHAR(250),
Lastname VARCHAR(250),
Biography TEXT
);

CREATE TABLE Movie(
id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
Title VARCHAR(250),
ReleaseYear INT,
Synopsis TEXT,
PosterURL VARCHAR(250),
Rating FLOAT,
tmdb_id INT UNIQUE,
director_id INT,
FOREIGN KEY (director_id) REFERENCES Director(id)
);



CREATE TABLE Genre(
id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
Label VARCHAR(250)
);

CREATE TABLE User_Movie (
    user_id INT NOT NULL,
    movie_id INT NOT NULL,
    PRIMARY KEY (user_id, movie_id),
    FOREIGN KEY (user_id) REFERENCES User(id) ON DELETE CASCADE,
    FOREIGN KEY (movie_id) REFERENCES Movie(id) ON DELETE CASCADE
);

CREATE TABLE Movie_Genre(
    movie_id INT NOT NULL,
    genre_id INT NOT NULL,
    PRIMARY KEY (movie_id, genre_id),
    FOREIGN KEY (movie_id) REFERENCES Movie(id) ON DELETE CASCADE,
    FOREIGN KEY (genre_id) REFERENCES Genre(id) ON DELETE CASCADE
)

;